version: 2.1
jobs:
  lint:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install Flake8
          command: pip install flake8
      - run:
          name: Run Flake8 on Backend
          command: flake8 backend/ --exclude=backend/myenv/lib/python3.9/site-packages/
  server_test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r backend/requirements.txt  # Adjust as needed
      - run:
          name: Start Server
          command: python backend/app.py
          background: true
      - run:
          name: Check if server is up
          command: |
            echo "Waiting for server to start..."
            sleep 5
            curl --fail http://localhost:5000  # Adjust the URL/port as necessary
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run tests
          command: echo 'replace me with real tests!' && false
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build an artifact
          command: touch example.txt
      - store_artifacts:
          path: example.txt
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy
          command: '#e.g. ./deploy.sh'
workflows:
  example:
    jobs:
      - lint
      - server_test:
          requires:
            - lint
      - test:
          requires:
            - server_test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
